# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_CLIENT_ID_HERE"
name = "Data Moodboard Integration"
handle = "data-moodboard-integration"
application_url = "https://datamoodboard.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"

[auth]
redirect_urls = [
  "http://localhost:3000/api/auth/shopify/callback",
  "https://datamoodboard.com/api/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[[extensions]]
type = "web_pixel"
name = "web_pixel"